-- AlterTable
ALTER TABLE "Profile" ALTER COLUMN "height" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "currentWeight" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "weightTarget" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "WeightHistory" ALTER COLUMN "currentWeight" SET DATA TYPE DOUBLE PRECISION;
